# Site
title:              Aishik Pyne
author:             Aishik Pyne
bio:                'Aishik Pyne'
description:        "Pyne"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aishikpyne.com" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    toc: true
    permalink: "/:categories/:title/"
- scope:
    path: '_posts/travel/'
  values:
    layout: post
    toc: true
    categories:
      - travel
# Jekyll
# permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
excerpt_separator: <!--more-->
kramdown:
  input: GFM
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  parse_block_html: true
mathjax:            true
collections: 
  travel:
    output: true
    permalink: /:collection/:title
  
sass:
  sass_dir: assets/css
  style: compact # possible values: nested expanded compact compressed

# Comments
disqus_shortname:   aishikpyne

# Social
analytics-id:       UA-128233180-1
twitter:            aishik_pyne
facebook:           default
instagram:          aishikpyne
github:             aishik-pyne
linkedin:           aishik-pyne
# personal
location:           Kolkata, India
phone:
email:              aishikpyne@gmail.com

# Plugins
plugins:
  - jekyll-toc
#   - jekyll-mentions
#   - jekyll-sitemap
#   - jekyll-feed
#   - jekyll-gist
#   - jekyll-paginate

# paginate: 6
# paginate_path: "/blog/page:num/"


jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old, .archive2018]
