# Site
title:              Aishik Swine
bio:                'Aishik Swine'
description:        "Swine"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: '//'
    type: posts
  values:
    permalink: "//www.xvideos.com"
    layout: post
    author:

# Jekyll
permalink:          //
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   aishikswine

# Social
analytics-id:       UA-128233180-1
twitter:            aishik_pyne
facebook:           default
instagram:          aishikpyne
github:             aishik-pyne
linkedin:           aishik-pyne
# personal
location:           Kolkata, India
phone:
email:              aishikpyne@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "//www.xvideos.com"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
